# -------------------------------------------------------------------------------------------------------
#                                            Environment (Example)
# -------------------------------------------------------------------------------------------------------
# LOOK_APPLICATION_NAME=look-service
# LOOK_APPLICATION_LOCAL_DATA=/tmp/look/data
# LOOK_SERVER_DOMAIN=domain.com.br
# LOOK_GCLOUD_CLIENT_ID=000000000000-c9qg23t7n1s50h2aspaec6l4ucavkjqn.apps.googleusercontent.com
# LOOK_GCLOUD_CLIENT_SECRET=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A
# LOOK_GCLOUD_SERVER_CLIENT_ID=000000000000-00ja0mia1h00es0c0v0pk0mse8qhpb00.apps.googleusercontent.com
# LOOK_GCLOUD_SERVER_CLIENT_SECRET=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
# LOOK_GCLOUD_TOKEN_STORAGE=tokens
# LOOK_GCLOUD_PROJECT_ID=look-project-000000
# LOOK_SERVER_ADDRESS=domain.com.br
# LOOK_SERVER_PORT=80
# LOOK_STORAGE_CREDENTIALS=classpath:serviceAccountKey.json
# LOOK_STORAGE_URL=https://look-project-000000-default-rtdb.firebaseio.com
# GOOGLE_APPLICATION_CREDENTIALS=classpath:credentials.json
# -------------------------------------------------------------------------------------------------------


server:
  port: ${LOOK_SERVER_PORT}
  address: ${LOOK_SERVER_DOMAIN:localhost}

springdoc:
  swagger-ui:
    oauth:
      clientId: ${LOOK_GCLOUD_CLIENT_ID}
      clientSecret: ${LOOK_GCLOUD_CLIENT_SECRET}
      realm: https://accounts.google.com
      appName: look
      scopeSeparator: openid email profile

spring:
  devtools:
    add-properties: false
  cloud:
    gcp:
      project-id: ${LOOK_GCLOUD_PROJECT_ID}
      credentials:
        location: ${GOOGLE_APPLICATION_CREDENTIALS}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${LOOK_GCLOUD_CLIENT_ID}
            client-secret: ${LOOK_GCLOUD_CLIENT_SECRET}
        resourceserver:
          jwt:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  application:
    name: look-service

firebase:
  serviceAccountKeyPath: ${LOOK_STORAGE_CREDENTIALS}
  databaseUrl: ${LOOK_STORAGE_URL}

look:
  cloud:
    gcp:
      server:
        client:
          id: ${LOOK_GCLOUD_SERVER_CLIENT_ID}
          secret: ${LOOK_GCLOUD_SERVER_CLIENT_SECRET}
          storage: ${LOOK_GCLOUD_TOKEN_STORAGE}
        token-url: https://oauth2.googleapis.com/token
        authorization-encoded-url: https://accounts.google.com/o/oauth2/auth
  application:
    data: ${LOOK_APPLICATION_LOCAL_DATA}
    name: ${LOOK_APPLICATION_NAME}
    caching:
        tll: 3600000 # milliseconds >> 3600s * 1000ms

logging:
  level:
    com.github.edulook: TRACE
    root: INFO
    org.springframework.web: DEBUG
