# Environment
# -------------------------
# LOOK_APPLICATION_NAME
# LOOK_GCLOUD_CLIENT_ID
# LOOK_GCLOUD_CLIENT_SECRET
# LOOK_GCLOUD_CLIENT_SECRET
# LOOK_GCLOUD_TOKEN_STORAGE
# LOOK_SERVER_ADDRESS
# LOOK_SERVER_PORT
# LOOK_STORAGE_CREDENTIALS
# LOOK_STORAGE_URL
#

server:
  port: ${LOOK_SERVER_PORT:8085}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            # IDs do cliente OAuth 2.0 - auth-look - Web
            client-id: ${LOOK_GCLOUD_CLIENT_ID:279941193466-b5qg23t7n1s50h2aspaec6l4ucavkjqn.apps.googleusercontent.com}
            client-secret: ${LOOK_GCLOUD_CLIENT_SECRET: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}
            # redirect-uri: https://laughing-eureka-q9xrp595j6534p69-8085.app.github.dev/v1/students/profile
        resourceserver:
          jwt:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  application:
    name: look-service

firebase:
  serviceAccountKeyPath: ${LOOK_STORAGE_CREDENTIALS:src/main/resources/serviceAccountKey.json}
  databaseUrl: ${LOOK_STORAGE_URL:https://look-project-400817-default-rtdb.firebaseio.com}

look:
  cloud:
    gcp:
      server:
        client:
          id: ${LOOK_GCLOUD_SERVER_CLIENT_ID:279941193466-64ja6mia1h00es4c0v4pk8mse8qhpb36.apps.googleusercontent.com}
          secret: ${LOOK_GCLOUD_SERVER_CLIENT_SECRET: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}
          storage: ${LOOK_GCLOUD_TOKEN_STORAGE:tokens}
        token-url: https://oauth2.googleapis.com/token
        authorization-encoded-url: https://accounts.google.com/o/oauth2/auth
  application:
    name: ${LOOK_APPLICATION_NAME:look-service}

logging:
  level:
    com.github.edulook: TRACE
    root: INFO
    org.springframework.web: DEBUG


# security:
#   basic:
#     enable: false 
#   oauth2:
  #     client:
  #       registration:
  #         google:
  #           clientId: 279941193466-b5qg23t7n1s50h2aspaec6l4ucavkjqn.apps.googleusercontent.com
  #           clientSecret: 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
  #           scope:
  #             - openid
  #             - email
  #             - profile
  #       provider:
  #         google:
  #           authorizationUri: https://accounts.google.com/o/oauth2/auth
  #           tokenUri: https://oauth2.googleapis.com/token
  #           userInfoUri: https://openidconnect.googleapis.com/v1/userinfo
  #           jwkSetUri: https://www.googleapis.com/oauth2/v1/certs
