server:
  address: localhost
  port: 8085

spring:
  cloud:
    gcp:
      project-id: look-project-400817
      credentials:
        location: classpath:credentials.json
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 279941193466-dukasel3kmn74s8qs76se3apuj9doilv.apps.googleusercontent.com
            client-secret: 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
        resourceserver:
          jwt:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  application:
    name: look-service

firebase:
  serviceAccountKeyPath: src/main/resources/serviceAccountKey.json
  databaseUrl: https://look-project-400817-default-rtdb.firebaseio.com

look:
  cloud:
    gcp:
      server:
        client:
          id: 279941193466-jurmlv7ru4q0mom9m5mpn0rdmn7bd0bo.apps.googleusercontent.com
          secret: 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
          storage: tokens
        token-url: https://oauth2.googleapis.com/token
        authorization-encoded-url: https://accounts.google.com/o/oauth2/auth
  application:
    name: look-service
    caching:
      tll: 3600000 # milliseconds >> 3600s * 1000ms

logging:
  level:
    com.github.edulook: DEBUG
    root: INFO
    org.springframework.web: DEBUG
